# Generated by Django 4.1 on 2022-09-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_phone_alter_user_qualification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysispatient',
            name='is_injury',
            field=models.IntegerField(choices=[(1, 'is injury'), (2, 'is healthy')], default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='types',
            field=models.IntegerField(choices=[(1, 'Doctor'), (2, 'reception')], default=1),
        ),
        migrations.AlterField(
            model_name='analysispatient',
            name='injurytype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='analysispatient',
            name='typetreatment',
            field=models.IntegerField(blank=True, choices=[(1, 'uyda'), (2, 'shifoxonada')], default=2, null=True),
        ),
    ]
