# Generated by Django 4.1 on 2022-09-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_info_pharmacy_analysispatient_quantitymedicine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='price',
            field=models.FloatField(),
        ),
    ]
